#Problem 4: Find the Imposter
'''Write a function find_difference() that takes two s
trings as parameters. The second string is generated by 
shuffling the first string and adding one more letter at a
 random position. Search for and return the added letter.

def find_difference(s1, s2):
    pass
Example Usage:

s1 = "abcd"
s2 = "baedc"
print(find_difference(s1, s2))
Example Output: e'''

'''
two strings, second string is shuffling teh first string 
with an additional eletteer in a random position
search for that letter and return the added letter

plan
iterate through s2 and compare with s1
return the one that doesnt match
'''

def find_difference(s1, s2):
    for i in s2:
        if i not in s1:
            return i
    return None

s1 = "abcd"
s2 = "baedc"
print(find_difference(s1, s2))